services:
  server:
    image: tugboatqa/debian
    default: true
    expose: 4000
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt install -y nodejs
      update:
        - bash $TUGBOAT_ROOT/.tugboat/scripts/server/update.sh
      build:
        - bash $TUGBOAT_ROOT/.tugboat/scripts/server/build.sh
      start:
        - npm run start --prefix ${TUGBOAT_ROOT}/server -- --max-http-header-size=2048 &
