services:
  server:
    image: tugboatqa/debian
    default: true
    expose: 4000
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        - apt install -y nodejs npm
      update:
        - bash $TUGBOAT_ROOT/.tugboat/scripts/server/update.sh
      build:
        - bash $TUGBOAT_ROOT/.tugboat/scripts/server/build.sh
      start:
        - npm run dev --prefix ${TUGBOAT_ROOT}/server &
