services:
  server:
    image: tugboatqa/debian
    expose: 4000
    default: true
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt install -y nodejs
      update:
        - ./scripts/server/update.sh
      build:
        - ./scripts/server/build.sh
